# Generated by Django 2.2 on 2021-08-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
