# Generated by Django 2.2 on 2021-08-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210822_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
