# Generated by Django 2.2 on 2021-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210823_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
